### ISSUE TITLE
Cannot compile with glibc >= 2.36

### ISSUE THREAD

**Issue by NicolasDerumigny** [atos-tools/qemu#19]
I stumble upon https://lore.kernel.org/qemu-devel/20230110174901.2580297-1-berrange@redhat.com/ . Can you backport the patch?

**Comment by NicolasDerumigny** [comment]
Corresponding fix commit is https://github.com/qemu/qemu/commit/6003159ce18faad4e1bc7bf9c85669019cd4950e

**Comment by guillon** [comment]
Done, integrated commit qemu@6003159 into branch: stable-7.2.plugins
Thanks for the report.
